### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by jonmchan** [sdague/znc-mailonmsg#2]
On occasion I get these:

```
*mailonmsg> Failed with 'utf-8' codec can't decode byte 0xbf in position 0: invalid start byte
 <*mailonmsg> Failed with 'utf-8' codec can't decode byte 0xbf in position 2: invalid start byte
 <*mailonmsg> Failed with 'utf-8' codec can't decode byte 0xbf in position 2: invalid start byte
 <*mailonmsg> Failed with 'utf-8' codec can't decode byte 0xbf in position 6: invalid start byte
 <*mailonmsg> Failed with 'utf-8' codec can't decode byte 0xbf in position 25: invalid start byte
 <*mailonmsg> Failed with 'utf-8' codec can't decode byte 0xbf in position 24: invalid start byte
 <*mailonmsg> Failed with 'utf-8' codec can't decode byte 0xbf in position 21: invalid start byte
 <*mailonmsg> Failed with 'utf-8' codec can't decode byte 0xbf in position 17: invalid start byte
 <*mailonmsg> Failed with 'utf-8' codec can't decode byte 0xbf in position 29: invalid start byte
 <*mailonmsg> Failed with 'utf-8' codec can't decode byte 0x85 in position 3: invalid start byte
```

Any way to suppress these? It would seem they are caused by other clients/people sending text encoded in different character encodings?

**Comment by sdague** [comment]
Yeh, I need to get to the bottom of what's triggering the messages. I'll figure out if I can this week some time.

**Comment by jonmchan** [comment]
here's a string that can trigger it everytime... Maybe we can use this to debug?

¬¬

Failed with 'utf-8' codec can't decode byte 0xac in position 0: invalid start byte

**Comment by jonmchan** [comment]
it would appear that it fails on all extended ascii characters:

http://www.ascii-code.com/

Perhaps there is a way to identify IRC character encoding or perhaps an IRC RFC specifies it to be in ascii and not utf-8?

**Comment by jonmchan** [comment]
more info: http://hinrik.net/irc-and-character-encoding/

**Comment by jonmchan** [comment]
The issue is more complex than we can resolve at this level. The error occurs at the C++ -> Python conversion level done by SWIG. The exception is thrown as soon as we try to read the message (msg.s). The best we can do is catch the unicode error, but we would lose the whole line of data and possibly miss a nick highlight. I will post an issue on the znc issues page and see if they can resolve the issue.

Somewhat similar issue:

http://stackoverflow.com/questions/2807887/cs-char-by-swig-got-problem-in-python-3-0

**Comment by sdague** [comment]
I'm not really maintaining this project any more, so I'm just going to close this out.
